-- ============================================================
-- FULLSOUND - Esquema inicial de base de datos (PostgreSQL)
-- ============================================================
-- Migracion V1: crea todas las tablas del dominio FullSound.
-- Generado a partir de las entidades JPA del proyecto.
-- ============================================================

-- ==================== TIPO USUARIO (Rol) ====================
CREATE TABLE IF NOT EXISTS tipo_usuario (
    id_tipo_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo            VARCHAR(50)  NOT NULL UNIQUE,
    descripcion     VARCHAR(255)
);

-- ==================== USUARIO ====================
CREATE TABLE IF NOT EXISTS usuario (
    id_usuario      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_usuario  VARCHAR(50)  NOT NULL UNIQUE,
    rut             VARCHAR(12),
    correo          VARCHAR(100) NOT NULL UNIQUE,
    "contraseña"    VARCHAR(255) NOT NULL,
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP,
    nombre          VARCHAR(100),
    apellido        VARCHAR(100)
);

CREATE INDEX IF NOT EXISTS idx_usuario_correo        ON usuario (correo);
CREATE INDEX IF NOT EXISTS idx_usuario_nombre_usuario ON usuario (nombre_usuario);

-- ==================== USUARIO_ROLES (join table) ====================
CREATE TABLE IF NOT EXISTS usuario_roles (
    usuario_id INTEGER NOT NULL,
    rol_id     INTEGER NOT NULL,
    PRIMARY KEY (usuario_id, rol_id),
    CONSTRAINT fk_usuario_roles_usuario FOREIGN KEY (usuario_id)
        REFERENCES usuario (id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_usuario_roles_rol FOREIGN KEY (rol_id)
        REFERENCES tipo_usuario (id_tipo_usuario) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_usuario_roles_rol ON usuario_roles (rol_id);

-- ==================== BEAT ====================
CREATE TABLE IF NOT EXISTS beat (
    id_beat         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo          VARCHAR(255) NOT NULL,
    slug            VARCHAR(255) UNIQUE,
    artista         VARCHAR(100),
    precio          INTEGER      NOT NULL,
    bpm             INTEGER,
    tonalidad       VARCHAR(10),
    duracion        INTEGER,
    genero          VARCHAR(50),
    emocion         VARCHAR(50),
    etiquetas       TEXT,
    descripcion     TEXT,
    imagen_url      VARCHAR(500),
    audio_url       VARCHAR(500),
    audio_demo_url  VARCHAR(500),
    reproducciones  INTEGER      NOT NULL DEFAULT 0,
    estado          VARCHAR(20)  NOT NULL DEFAULT 'DISPONIBLE',
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_beat_slug   ON beat (slug);
CREATE INDEX IF NOT EXISTS idx_beat_titulo ON beat (titulo);
CREATE INDEX IF NOT EXISTS idx_beat_genero ON beat (genero);

-- ==================== COMPRA (Pedido) ====================
CREATE TABLE IF NOT EXISTS compra (
    id_compra      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario     INTEGER      NOT NULL,
    numero_pedido  VARCHAR(50)  UNIQUE,
    fecha_compra   TIMESTAMP    NOT NULL,
    total          INTEGER      NOT NULL,
    estado         VARCHAR(20)  NOT NULL DEFAULT 'PENDIENTE',
    metodo_pago    VARCHAR(20),
    CONSTRAINT fk_compra_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_compra_numero_pedido ON compra (numero_pedido);
CREATE INDEX IF NOT EXISTS idx_compra_usuario       ON compra (id_usuario);

-- ==================== COMPRA_DETALLE (PedidoItem) ====================
CREATE TABLE IF NOT EXISTS compra_detalle (
    id_detalle      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_compra       INTEGER      NOT NULL,
    id_beat         INTEGER      NOT NULL,
    nombre_item     VARCHAR(255) NOT NULL,
    cantidad        INTEGER      NOT NULL DEFAULT 1,
    precio_unitario INTEGER      NOT NULL,
    CONSTRAINT fk_compra_detalle_compra FOREIGN KEY (id_compra)
        REFERENCES compra (id_compra) ON DELETE CASCADE,
    CONSTRAINT fk_compra_detalle_beat FOREIGN KEY (id_beat)
        REFERENCES beat (id_beat) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_compra_detalle_compra ON compra_detalle (id_compra);
CREATE INDEX IF NOT EXISTS idx_compra_detalle_beat   ON compra_detalle (id_beat);

-- ==================== PAGO ====================
CREATE TABLE IF NOT EXISTS pago (
    id_pago                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_compra                INTEGER      NOT NULL,
    stripe_payment_intent_id VARCHAR(255) UNIQUE,
    stripe_charge_id         VARCHAR(255),
    estado                   VARCHAR(20)  NOT NULL DEFAULT 'PENDIENTE',
    monto                    INTEGER      NOT NULL,
    moneda                   VARCHAR(3)   DEFAULT 'CLP',
    created_at               TIMESTAMP    NOT NULL,
    processed_at             TIMESTAMP,
    CONSTRAINT fk_pago_compra FOREIGN KEY (id_compra)
        REFERENCES compra (id_compra) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_pago_compra ON pago (id_compra);

-- ==================== DATOS INICIALES (Roles) ====================
INSERT INTO tipo_usuario (tipo, descripcion) VALUES
    ('administrador', 'Administrador del sistema'),
    ('cliente', 'Usuario cliente')
ON CONFLICT (tipo) DO NOTHING;
