-- ============================================================
-- FULLSOUND - Migracion V4: favoritos / wishlist de usuarios
-- ============================================================
-- Tabla join que permite a un usuario marcar beats como favoritos.
-- ============================================================

CREATE TABLE IF NOT EXISTS usuario_favorito (
    id_favorito   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario    INTEGER NOT NULL,
    id_beat       INTEGER NOT NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id_usuario, id_beat),
    CONSTRAINT fk_usuario_favorito_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_usuario_favorito_beat FOREIGN KEY (id_beat)
        REFERENCES beat (id_beat) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_usuario_favorito_usuario ON usuario_favorito (id_usuario);
CREATE INDEX IF NOT EXISTS idx_usuario_favorito_beat   ON usuario_favorito (id_beat);
