-- ============================================================
-- FULLSOUND - Migracion V5: resenas / valoraciones de beats
-- ============================================================
-- Permite a los usuarios dejar una valoracion (1-5) y un
-- comentario sobre un beat. Un usuario solo puede dejar una
-- resena por beat.
-- ============================================================

CREATE TABLE IF NOT EXISTS review (
    id_review    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_beat      INTEGER NOT NULL,
    id_usuario   INTEGER NOT NULL,
    rating       INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comentario   TEXT,
    created_at   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP,
    UNIQUE (id_beat, id_usuario),
    CONSTRAINT fk_review_beat FOREIGN KEY (id_beat)
        REFERENCES beat (id_beat) ON DELETE CASCADE,
    CONSTRAINT fk_review_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_review_beat    ON review (id_beat);
CREATE INDEX IF NOT EXISTS idx_review_usuario ON review (id_usuario);
