-- ============================================================
-- FULLSOUND - Migracion V6: notificaciones in-app
-- ============================================================
-- Notificaciones dirigidas a un usuario (compra, resena, stock,
-- sistema, etc.) con marca de leido y timestamp.
-- ============================================================

CREATE TABLE IF NOT EXISTS notificacion (
    id_notificacion  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario       INTEGER NOT NULL,
    tipo             VARCHAR(50)  NOT NULL,
    mensaje          VARCHAR(500) NOT NULL,
    leido            BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       TIMESTAMP,
    CONSTRAINT fk_notificacion_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_notificacion_usuario ON notificacion (id_usuario);
CREATE INDEX IF NOT EXISTS idx_notificacion_leido   ON notificacion (id_usuario, leido);
